### ISSUE TITLE
Account linking before logging in

### ISSUE THREAD

**Issue by nikosdion** [joomla-extensions/facebook-auth#2]
Currently the only way to link your Facebook account to your Joomla user account is by logging in from a Facebook account which uses the same email address as you do in Joomla. This is problematic because:
- It's not intuitive for the users.
- Some people, myself included, use a different email on Facebook than they do on their site.
- There is no way to know if you have linked your account already.
- There are security consideration regarding email matching outlined below.

I will add a user plugin which will let you link (and unlink) your Facebook account to your Joomla! user account.

_Note_: in case on FB account is linked to multiple user accounts the login will work with whichever user account is returned first by the database.

**Comment by jeckodevelopment** [comment]
Is this relevant also when people register using Facebook? or does the plugin just allow authentication/login?

**Comment by nikosdion** [comment]
I mean, the entire point of this issue is for me to add a user plugin which lets you link / unlink your Facebook account:

> I will add a user plugin which will let you link (and unlink) your Facebook account to your Joomla! user account.

**Comment by jeckodevelopment** [comment]
Got it.
Thanks

**Comment by nikosdion** [comment]
I am not interested in participating in a project that lacks transparency and hides behind "non-disclosure agreements" to hide its actions from the public. I only ever came to Joomla because it was supposed to be the ultimately democratic, transparent governance model. It has failed that basic promise given back in 2005. Bye.
